#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

Import('BuildEnv')
env = BuildEnv.Clone()

base_path = '#src/contrail-common/libpartition/'

sources = ['setup.py', 'requirements.txt']
sources += env.AddPythonSources('libpartition')

sdist_gen = env.Command(
    '/pip/libpartition-0.1.dev0-py3-none-any.whl', sources,
    'cd ' + Dir(base_path).path + ' && ' + 'python3 setup.py bdist_wheel --dist-dir /pip')
env.Alias('install', sdist_gen)
